[project]
name = "simple-pipecat-bot"
version = "0.1.0"
description = "pipecat-demos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.0",
    "pipecat-ai[google,silero,webrtc]>=0.0.103",
    "pydantic-settings>=2.13.1",
    "uvicorn>=0.41.0",
]


[tool.ruff.lint]
select = ["I"]
