[project]
name = "pipecat-demos"
version = "0.1.0"
description = "my pipecat-demos repo for different use cases"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.2",
    "langchain-nvidia-ai-endpoints>=1.2.0",
    "langchain-qdrant>=1.1.0",
    "loguru>=0.7.3",
    "pipecat-ai[nvidia,silero,webrtc]>=0.0.104",
    "pydantic-settings>=2.13.1",
    "uvicorn[standard]>=0.41.0",
]


[tool.ruff.lint]
select = ["I"]
